### ISSUE TITLE
Menu email has changed :cry:

### ISSUE THREAD

**Issue by paulbeattie** [JordanAdams/yumyum-menu#1]
So the menu email has changed 😢. It's now entirely HTML based which is sad.

The downside to this new-fangled HTML future is that there is no single identifier to help differentiate the image URL from the rest of the body. The best approach we're likely to have with this is that we regex `gallery.mailchimp.com` and then match on the second URL and pull it out.

Alternatively, we can consume the nice handy [list of newsletters](https://us3.campaign-archive.com/home/?u=960535dd9067bb938d37f961b&id=c121c49538) provided by Mailchimp 🙌. The nice folks at Mailchimp also provide a [handy RSS feed](https://us3.campaign-archive.com/feed?u=960535dd9067bb938d37f961b&id=c121c49538).

Sadly with the second approach we still need to parse the HTML and find the image, handily for each email there's a handy class, `mcnImage` that is applied to UGC assets, there are 2 UGC assets in the body of the email. For some reason, these are also applied in the email version but they've got a funky ID prepended.

**Comment by JordanAdams** [comment]
So one kinda hacky way I figured to do this was to grab all the image URLs and filter out the one for the logo since it looks to be the same URL in each (https://gallery.mailchimp.com/960535dd9067bb938d37f961b/images/36ca8e6b-70cc-4ab5-82ca-952c29e8b00c.png)

Failing that we could go to the extent of fetching both images and keeping the largest one.

Both aren't ideal but assuming their emails stay roughly the same, it _should_ work.
